version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_discord_bot
    command: --replSet rs0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
      - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js

volumes:
  dbdata: {}
