{
  'parser': '@typescript-eslint/parser',
  'parserOptions': { 'ecmaVersion': 12, 'sourceType': 'module' },
  'plugins': ['@typescript-eslint', 'import'],
  'extends':
    ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],

  'rules':
    {
      '@typescript-eslint/no-unused-vars': 'error',
      '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
      'import/order': [
        'error',
        {
          'groups': ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'pathGroups': [
            {
              'pattern': 'react',
              'group': 'external',
              'position': 'before',
            },
          ],
          'pathGroupsExcludedImportTypes': ['react'],
          'newlines-between': 'always',
          'alphabetize': { 'order': 'asc', 'caseInsensitive': true },
        },
      ],
    },

}
