{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint",
    "import",
    "prettier"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  "rules": {
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/consistent-type-definitions": ["error", "type"],
    "import/order": [
      "error",
      {
        "groups": ["builtin", "external", "internal", "parent", "sibling", "index"],
        "newlines-between": "always",
        "alphabetize": {
          "order": "asc",
          "caseInsensitive": true
        }
      }
    ],
    "import/no-duplicates": "error",
    "import/newline-after-import": "error",
    "import/no-cycle": "error",
    "import/no-self-import": "error",
    "prettier/prettier": [
      "error",
      {
        "semi": false,
        "singleQuote": true,
        "arrowParens": "always",
        "trailingComma": "all",
        "useTabs": false,
        "overrides": [
          {
            "files": ["*.md"],
            "options": {
              "printWidth": 80
            }
          }
        ]
      }
    ]
  }
}
