{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module",
    "project": "./config/tsconfig.eslint.json"
  },
  "plugins": [
    "@typescript-eslint",
    "simple-import-sort",
    "promise",
    "prettier",
  ],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:promise/recommended",
  ],
  "rules": {
    "no-console": "error",
    "@typescript-eslint/prefer-readonly": "error",
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/consistent-type-definitions": ["error", "type"],
    "@typescript-eslint/promise-function-async": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/explicit-function-return-type": ["error", {
        "allowExpressions": true
    }],
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "variable",
        "format": ["camelCase"]
      },
      {
      "selector": "variable",
      "modifiers": ["const", "global"],
      "format": ["camelCase", "UPPER_CASE"],
      "leadingUnderscore": "allow",
      "trailingUnderscore": "allow"
      }
    ],
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
    "promise/always-return": "error",
    "promise/no-nesting": "warn",
    "prettier/prettier": [
      "error",
      {
        "semi": false,
        "singleQuote": true,
        "arrowParens": "always",
        "trailingComma": "all",
        "useTabs": false,
        "overrides": [
          {
            "files": ["*.md"],
            "options": {
              "printWidth": 80
            }
          }
        ]
      }
    ]
  }
}
