name: Deploy
on:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true
      TOKEN:
        required: true
      CLIENT_ID:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'src/**/*')
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  update:
    name: Update bot commands
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'src/commands/**/*')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies (if cache miss)
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Upload command list
        run: npm run commands:update
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
