name: Quality

on: [workflow_call]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies (if cache miss)
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies (if cache miss)
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Check Prettier formatting
        run: npm run prettier
